name: Deploy Docker image to ECR and ECS - DEV

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login no ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 731184207167.dkr.ecr.us-east-2.amazonaws.com

      - name: Build da imagem Docker
        run: |
          docker build -t lapasta-api-dev .

      - name: Tag e push da imagem
        run: |
          docker tag lapasta-api-dev:latest 731184207167.dkr.ecr.us-east-2.amazonaws.com/lapasta-api-dev:latest
          docker push 731184207167.dkr.ecr.us-east-2.amazonaws.com/lapasta-api-dev:latest

      - name: Forçar novo deploy no ECS
        run: |
          aws ecs update-service \
            --cluster lapasta-api-dev-cluster \
            --service lapasta-api-dev-service \
            --force-new-deployment
